name: AbstractCheckerTestCaseTest

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    abstract_checker_test_case_test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.3'
                    coverage: none

            -   run: composer require phpunit/phpunit
                working-directory: ./tests

            -   run: composer require symplify/easy-coding-standard
                working-directory: ./tests

            -   run: composer require symplify/easy-testing
                working-directory: ./tests

            -   run: composer require squizlabs/php_codesniffer
                working-directory: ./tests

            -   run: vendor/bin/phpunit AbstractCheckerTestCaseTest.php
                working-directory: ./tests
